### ISSUE TITLE
ES6 webpack uirouter issue

### ISSUE THREAD

**Issue by andypeng2015** [nearbycoder/boilerplate-es6-angular-webpack#1]
Hi Josh,

I am following your webpack demo to create angular 1.x app, the only issue is when i compile with source-map, it works, but without source-map the router doesnt work and there is no error in console, pls kindly advise, thanks a lot in advance

@nearbycoder

**Comment by nearbycoder** [comment]
Can you let me know what you are using to run it without sourcemaps? On my side I was able to build using build2 although I did have to remove `react` from the presets in the webpack.config.js. As well I am not showing the same webpack.config.js file as you are missing `ng-annotate` and I see that you are using $inject instead.

**Comment by andypeng2015** [comment]
hi Josh,
 I use build2 to build, whis without source-map, and the new and edit ui router doesnt work but when i use build3, the new and edit button works, so what you suggested is to remove the $inject and use ng-annotate? thanks

@nearbycoder

**Comment by andypeng2015** [comment]
hi Josh,

when I use npm run build2 to build, thereafter when i open ngTodo.html and click add button at right bottom side, i have some injection error, pls advise, thanks a lot

![error](https://cloud.githubusercontent.com/assets/24508594/22156239/5d36727e-df6d-11e6-912a-e01f7c26b68c.png)


@nearbycoder

**Comment by nearbycoder** [comment]
@andypeng2015  I created a PR against your repo, check it out and see if that works for you.

**Comment by andypeng2015** [comment]
hi Josh,

no more provider issue, thanks, but 2 minor issues here:
1: when i click edit button on existing card, the cardform is blank even though the cardId is passed in, pls advise why i cannot get cardId by self.cardId

2: when i make /index as parent router of /new, and if I click new button, it goes to another page, but when i make /index as parent of /edit, and click edit button, it pops up in same page, why ui-router has different behaviour,


thanks a lot 

@nearbycoder

**Comment by andy2046** [comment]
i committed the change to make /index as parent of /new

**Comment by andypeng2015** [comment]
hi Josh, 

for issue 1, it only happens in win 64 bit os, not in win 32bit os, any idea why os causes this error? thanks

@nearbycoder

**Comment by andypeng2015** [comment]
issues resolved, thanks
