### ISSUE TITLE
question how to exclude webpack.karma.context.js from coverage report

### ISSUE THREAD

**Issue by andypeng2015** [nearbycoder/boilerplate-es6-angular-webpack#2]
Hi Josh,
Not sure if you are familiar with karma, I found my webpack.karma.context.js is included in coverage report,how can I exclude it? thanks a lot 

![context](https://cloud.githubusercontent.com/assets/24508594/22727462/eb49d4e8-ee13-11e6-8600-355c96ca3119.JPG)

**webpack.karma.context.js**
`let context = require.context('./app', true, /\.js/);
context.keys().forEach(context);`

**Comment by nearbycoder** [comment]
I am not familiar myself but this stackoverflow answer may help you out http://stackoverflow.com/questions/29135575/how-do-i-exclude-files-from-karma-code-coverage-report

**Comment by andypeng2015** [comment]
hi Josh, I tried this before but it doesn't solve my issue, anyway thanks for the info
